apiVersion: v1
kind: Service
metadata:
  name: consumer-lotso-docs-svc
  namespace: documents
spec:
  selector:
    app: consumer-lotso-docs
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP